- name: Details of DevOps Course 
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS #string
    DURATION: 120 #number
    topics: #list
    - linux
    - ansible
    - terraform
    - docker
    - k8
    live: false #boolean
    tools: #maps/dictionary
     ci: jenkins #string
     cm: ansible
     cloud: aws
     aws:
     - IAM
     - S3
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi i am learning {{COURSE}}, duration is {{DURATION}}, topics are: {{topics}}, then live:{{live}} and tools: {{tools}}"