- name: install nginx
  become: yes
  hosts: anisble_node_private_IP
  tasks:
  - name: gathering the facts from server
    ansible.builtin.debug: 
     msg: "{{ansible_facts}}"
    
  - name: install nginx if redhat
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == "RedHat"

  - name: install ngnix if Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
    
