#google using filters to manipulate data-> handling undefined variables,uppercase,lower,unique,min and max,convert map to list/list to map,IP address filter

- name: filter in ansible
  hosts: local
  connection: local
  tasks:
  - name: varibale not defined
    ansible.builtin.debug:
     msg: "{{course | default ('ansible')}}"   #here course variable has not defind so in ansible by using default filter we can achieve varibales
  - name: print varibale in uppercase
    vars:
      greeting: good morning
    ansible.builtin.debug:
      msg: "{{greeting | upper }}"

  - name: print varibale in lowercase
    vars:
      Wishes: HappY BIrthday
    ansible.builtin.debug:
     msg: "{{ Wishes | lower }}"
  
  - name: print unique values
    vars:
      number: [ 1,2,3,4,5,6,2,5,4,1 ]
    ansible.builtin.debug:
     msg: "{{number | unique }}"

  - name: print the numbers min and max
    vars:
      number: [ 1,2,3,4,5,6,2,5,4,1 ]
    ansible.builtin.debug:
     msg: "{{number | max , number | min}}"

  - name: print the o/p form map to dictionary
    vars:
      course:
        name: Devops with aws
        duration: 120hrs
        trianer: siva
    ansible.builtin.debug:
     msg: "{{course | dict2items}}"

  - name: print the o/p from dictionary to map
    vars:
     course:
      - { "key": "name", "value": "Devops with aws"}
      - { "key": "duration", "value": "120hrs" }
      - { "key": "trianer", "value": "siva" }
    ansible.builtin.debug:
     msg: "{{course | items2dict}}"  

  - name: to check valid ip address or not
    vars:
      myip: "123.234.12.9"  #if ip is valid result is true else false   
    ansible.builtin.debug:
      msg: "{{myip | ansible.utils.ipv4}}"
       # in result it shows some packages needs to be install
       # 1.anisble  --version
       # 2.pip3.9 install netaddr

      




